---
# Install required packages for Docker

- name: Install required packages
  become: yes
  shell:
    cmd: apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release git

  register: pkg_install

- name: Add Docker GPG key
  become: yes
  shell:
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  register: gpg_result

# Add Docker repository
- name: Add Docker repository
  become: yes
  shell: |
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
    apt-get update
  register: repo_result

# Install Docker Engine
- name: Install Docker
  become: yes
  shell:
    cmd: apt-get install -y docker-ce docker-ce-cli containerd.io
  register: docker_result

# Make sure Docker service is running
- name: Start Docker service
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

# Install Docker Compose
- name: Install Docker Compose
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "0755"

# Print Docker versions
- name: Print Docker versions
  debug:
    msg:
      - "Docker version: {{ docker_version.stdout }}"
      - "Docker Compose version: {{ docker_compose_version.stdout }}"

# Add current user to docker group to avoid using sudo
- name: Add user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: yes
