---
# Install required packages for Docker

# Clean apt lock files and ensure proper permissions
# - name: Fix apt permissions and clear locks
#   become: yes
#   shell: |
#     # Remove lock files
#     rm -f /var/lib/apt/lists/lock /var/cache/apt/archives/lock /var/lib/dpkg/lock*
#     # Ensure proper permissions on apt directories
#     chown -R root:root /var/lib/apt/lists/
#     chmod -R 755 /var/lib/apt/lists/
#     mkdir -p /var/lib/apt/lists/partial
#     chmod 755 /var/lib/apt/lists/partial
#   args:
#     warn: no
#   changed_when: false
#   ignore_errors: yes

# Update apt cache separately
- name: Update apt cache
  become: yes
  shell: apt-get update
  args:
    warn: no
  changed_when: false
  ignore_errors: no
  register: apt_update

- name: Install required packages
  become: yes
  shell: apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release git
  args:
    warn: no
  register: pkg_install

- name: Add Docker GPG key
  become: yes
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    warn: no
  register: gpg_result

# Add Docker repository
- name: Add Docker repository
  become: yes
  shell: |
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
    apt-get update
  args:
    warn: no
  register: repo_result

# Install Docker Engine
- name: Install Docker
  become: yes
  shell: apt-get install -y docker-ce docker-ce-cli containerd.io
  args:
    warn: no
  register: docker_result

# Make sure Docker service is running
- name: Start Docker service
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

# Install Docker Compose
- name: Install Docker Compose
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "0755"

# Verify Docker installation
- name: Check Docker version
  command: docker --version
  register: docker_version
  changed_when: false

# Verify Docker Compose installation
- name: Check Docker Compose version
  command: docker-compose --version
  register: docker_compose_version
  changed_when: false

# Print Docker versions
- name: Print Docker versions
  debug:
    msg:
      - "Docker version: {{ docker_version.stdout }}"
      - "Docker Compose version: {{ docker_compose_version.stdout }}"

# Add current user to docker group to avoid using sudo
- name: Add user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: yes
