---
# Install required packages for Docker
- name: Install required packages
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - git
    state: present
    update_cache: yes
    force_apt_get: yes

- name: Add Docker GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# Add Docker repository
- name: Add Docker repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
  register: repo_result
  retries: 3
  delay: 5
  until: repo_result is success

# Install Docker Engine
- name: Install Docker
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
    force_apt_get: yes
  register: docker_result
  retries: 3
  delay: 5
  until: docker_result is success

# Make sure Docker service is running
- name: Start Docker service
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

# Install Docker Compose
- name: Install Docker Compose
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "0755"

# Verify Docker installation
- name: Check Docker version
  command: docker --version
  register: docker_version
  changed_when: false

# Verify Docker Compose installation
- name: Check Docker Compose version
  command: docker-compose --version
  register: docker_compose_version
  changed_when: false

# Print Docker versions
- name: Print Docker versions
  debug:
    msg:
      - "Docker version: {{ docker_version.stdout }}"
      - "Docker Compose version: {{ docker_compose_version.stdout }}"

# Add current user to docker group to avoid using sudo
- name: Add user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: yes
