# ---
- include_role:
    name: k3s

- include_role:
    name: dt-operator
  vars:
    operator_mode: "cloudNativeFullStack"
    dt_operator_release: "v1.6.0"
    host_group: k8s_multi_prod

- include_role:
    name: app-easytrade

- include_role:
    name: app-hipstershop
