---
- debug:
    msg: "Hello from your external use case!"

- include_tasks:
    file: docker.yml

- include_role:
    name: dt-oneagent-classic

#- include_tasks:
#    file: easy-trade-docker.yml
- include_tasks:
    file: easy-travel-docker.yml
