---
- include_role:
    name: k3s

- include_role:
    name: dt-operator
  vars:
    operator_mode: "cloudNativeFullStack"

- include_role:
    name: app-easytrade

- include_role:
    name: app-hipstershop