# Copyright 2024 Dynatrace LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: Install Monaco
  include_role:
    name: monaco-v2

- include_role:
    name: dt-access-token
  vars:
    access_token_var_name: "monaco_api_token"
    access_token_scope:
      [
        "CaptureRequestData",
        "credentialVault.read",
        "credentialVault.write",
        "DataExport",
        "DataPrivacy",
        "ExternalSyntheticIntegration",
        "ReadConfig",
        "WriteConfig",
        "events.ingest",
        "settings.read",
        "settings.write",
        "slo.read",
        "slo.write",
      ]

- set_fact:
    monaco_projects_folder: "{{ role_path }}/files/easytrade/monaco"

- name: Monaco - Deploy configuration
  include_role:
    name: monaco-v2
    tasks_from: apply-monaco
  vars:
    monaco_manifest_path: "{{ monaco_projects_folder }}/manifest.yaml"
    monaco_environment:
      TENANT_URL: "{{ extra_vars.dt_environment_url_gen3.rstrip('/') }}"
      TENANT_TOKEN: "{{ monaco_api_token }}"
      CLIENT_ID: "{{ extra_vars.dt_oauth_client_id }}"
      CLIENT_SECRET: "{{ extra_vars.dt_oauth_client_secret }}"
      SLACK_TOKEN: "{{ extra_vars.slack_bot_token | default('abc123') }}"

