manifestVersion: 1.0
projects:
  - name: auto-tags
  # - name: bucket
  # - name: builtinopenpipeline.spans.pipelines
  - name: management-zone
environmentGroups:
  - name: development
    environments:
      - name: dev
        url:
          type: environment
          #value: DT_PLATFORM_TENANT_URL
          value: DT_CLASSIC_TENANT_URL 
        auth:
          token:
            type: environment
            name: DT_TOKEN
          # oAuth:
          #   clientId:
          #     type: environment
          #     name: DT_OAUTH_CLIENT_ID
          #   clientSecret:
          #     type: environment
          #     name: DT_OAUTH_CLIENT_SECRET
          #   tokenEndpoint:
          #     type: environment
          #     value: DT_OAUTH_SSO_ENDPOINT