manifestVersion: 1.0
projects:
  - name: document-notebook
  - name: application
  - name: bizevents-processing-rules
  - name: bizevents
  - name: custom-service
  - name: builtinmonitoring.slo
  - name: auto-tags
  - name: management-zone
  - name: config
    path: config
    type: grouping
  # - name: builtinsynthetic.http.assigned-applications
  # - name: builtinsynthetic.http.name
  # - name: builtinsynthetic.http.outage-handling
  # - name: builtinsynthetic.http.performance-thresholds
  # - name: builtinsynthetic.http.scheduling
  # - name: builtinsynthetic.http.status
  # - name: builtinsynthetic.http.steps
environmentGroups:
  - name: development
    environments:
      - name: dev
        url:
          type: environment
          value: DT_PLATFORM_TENANT_URL 
        auth:
          token:
            type: environment
            name: DT_TOKEN
          oAuth:
            clientId:
              type: environment
              name: DT_OAUTH_CLIENT_ID
            clientSecret:
              type: environment
              name: DT_OAUTH_CLIENT_SECRET
            tokenEndpoint:
              type: environment
              value: DT_OAUTH_SSO_ENDPOINT