manifestVersion: 1.0
projects:
  - name: application
  - name: builtintags.auto-tagging
  - name: bizevents
  - name: bizevents-processing-rules
  - name: config
    path: config
    type: grouping
  - name: document-notebook
  - name: custom-service
  - name: builtinmanagement-zones
  - name: dashboard
  - name: builtinlogmonitoring.log-storage-settings
  # - name: builtinmetric.metadata
  # - name: builtinmonitoring.slo
  # - name: builtinsynthetic.http.assigned-applications
  # - name: builtinsynthetic.http.name
  # - name: builtinsynthetic.http.outage-handling
  # - name: builtinsynthetic.http.performance-thresholds
  # - name: builtinsynthetic.http.scheduling
  # - name: builtinsynthetic.http.status
  # - name: builtinsynthetic.http.steps
environmentGroups:
  - name: development
    environments:
      - name: dev
        url:
          type: environment
          value: DT_PLATFORM_TENANT_URL 
        auth:
          token:
            type: environment
            name: DT_TOKEN
          oAuth:
            clientId:
              type: environment
              name: DT_OAUTH_CLIENT_ID
            clientSecret:
              type: environment
              name: DT_OAUTH_CLIENT_SECRET
            tokenEndpoint:
              type: environment
              value: DT_OAUTH_SSO_ENDPOINT