configs:
- id: 608a4998-68c9-3a18-bd45-33451fe5d4d4
  config:
    template: 608a4998-68c9-3a18-bd45-33451fe5d4d4.json
    skip: false
    originObjectId: vu9U3hXa3q0AAAABABZidWlsdGluOm1vbml0b3Jpbmcuc2xvAAZ0ZW5hbnQABnRlbmFudAAkOGU3MjJjMGUtMWVmZC0zZmE4LWE3ODQtNTE5NDUxYzA2MDE1vu9U3hXa3q0
  type:
    settings:
      schema: builtin:monitoring.slo
      schemaVersion: 6.0.14
      scope: environment
- id: 8e40dcb4-3907-33aa-af1f-e2a2e5fb2bb2
  config:
    template: 8e40dcb4-3907-33aa-af1f-e2a2e5fb2bb2.json
    skip: false
    originObjectId: vu9U3hXa3q0AAAABABZidWlsdGluOm1vbml0b3Jpbmcuc2xvAAZ0ZW5hbnQABnRlbmFudAAkOGU0MGRjYjQtMzkwNy0zM2FhLWFmMWYtZTJhMmU1ZmIyYmIyvu9U3hXa3q0
  type:
    settings:
      schema: builtin:monitoring.slo
      schemaVersion: 6.0.14
      scope: environment
