- op: add
  path: /spec/template/metadata/labels/app.kubernetes.io~1version
  value: "1.0.0"

- op: add
  path: /spec/template/metadata/labels/app.kubernetes.io~1part-of
  value: easytrade

- op: add
  path: /spec/template/metadata/labels/team
  value: alpha

- op: add
  path: /spec/template/metadata/labels/stage
  value: prod
